### ISSUE TITLE
Sublime Text 2 support possible?

### ISSUE THREAD

**Issue by oliverwilliams84** [facelessuser/sublime-regex#1]
Hey man,

Coming into this with limited knowledge of how much work goes into this but is a ST2 version possible? It's hard to keep backwards compatability when forced to use the re module

**Comment by facelessuser** [comment]
It's possible, I just don't have interest in personally supporting the ST2 part; especially not with this dependency as it requires me to acquire the wheels for windows, build the OSX versions, and build the 32bit and 64bit versions on a docker images (or virtual box image) with really old Linux release to maximize the linux versions it will work on.  It's just more work than I want to take on to provide versions for Python 2.6 (ST2's version).

Anyone is welcome to provide the ST2 parts via pull requests.  But I would leave it up to others to this, and I will leave maintenance of new updates up to them as well while I focus on ST3 which I currently use.

**Comment by facelessuser** [comment]
As there is no actionable item, Im closing this.
